pdf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from pdf_app import views

urlpatterns = [
    path('', views.cases_view, name='cases'),
    path('case/<int:pk>/', views.case_view, name='case'),
    path('case/download/<int:pk>/', views.case_download, name='case_download'),
    path('admin/', admin.site.urls),
    path('martor/', include('martor.urls')),
    path('advanced_filters/', include('advanced_filters.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

pdf_app/models.py
import io
import os

from django.db import models
from martor.models import MartorField
# from reportlab.pdfgen import canvas
# from reportlab.lib.pagesizes import letter

from pdf.settings import MEDIA_ROOT

# Create your models here.


class Case(models.Model):
    title = models.CharField(max_length=1000)
    summary = MartorField()
    TYPE_CHOICE = {
        ('type1', 'type1'),
        ('type2', 'type2')
    }
    type = models.CharField(choices=TYPE_CHOICE, max_length=100)
    file1 = models.FileField(upload_to='upload', null=True, blank=True)
    file2 = models.FileField(upload_to='upload', null=True, blank=True)
    report = models.FileField(null=True, blank=True)

    def __str__(self):
        return self.title

    # def save(self, *args, **kwargs):
    #     file = os.path.join(MEDIA_ROOT, self.title + '_pdf.pdf')
    #
    #     # Create the PDF object, using the buffer as its "file."
    #     p = canvas.Canvas(file, pagesize=letter)
    #
    #     # Draw things on the PDF. Here's where the PDF generation happens.
    #     # See the ReportLab documentation for the full list of functionality.
    #     p.setLineWidth(.3)
    #     p.setFont('Helvetica', 12)
    #
    #     p.drawString(30, 750, self.title)
    #     p.drawString(30, 735, self.summary)
    #     p.drawString(500, 750, "12/12/2010")
    #     p.line(480, 747, 580, 747)
    #
    #     p.drawString(275, 725, 'AMOUNT OWED:')
    #     p.drawString(500, 725, "$1,000.00")
    #     p.line(378, 723, 580, 723)
    #
    #     p.drawString(30, 703, 'RECEIVED BY:')
    #     p.line(120, 700, 580, 700)
    #     p.drawString(120, 703, "JOHN DOE")
    #
    #     # Close the PDF object cleanly, and we're done.
    #     p.showPage()
    #     p.save()
    #
    #     self.report = file
    #
    #     super(Case, self).save(*args, **kwargs)


class This(models.Model):
    this = models.CharField(max_length=1000)
    this1 = models.CharField(max_length=1000)
    this2 = models.CharField(max_length=1000)
    case = models.ForeignKey(Case, on_delete=models.CASCADE)

    def __str__(self):
        return self.this + '-' + \
               self.this1 + '-' + \
               self.this2


class That(models.Model):
    that = models.CharField(max_length=1000)
    case = models.ForeignKey(Case, on_delete=models.CASCADE)

pdf_app/views.py
import tempfile

from django.shortcuts import render, get_object_or_404

from weasyprint import HTML, CSS
from django.template.loader import get_template, render_to_string
from django.http import HttpResponse

# Create your views here.
from pdf_app.models import Case


def cases_view(request):
    """Display all blog posts"""

    cases = Case.objects.all()

    return render(request, 'index.html', {'cases': cases})


def case_view(request, pk):
    """Display specific blog posts"""

    case = get_object_or_404(Case, pk=pk)

    return render(request, 'case.html', {'case': case})


def case_download(request, pk):
    """Generate pdf."""
    # Model data
    case = Case.objects.filter(pk=pk)

    # Rendered
    html_string = render_to_string('case_download.html', {'case': case})
    html = HTML(string=html_string)
    result = html.write_pdf()

    # Creating http response
    response = HttpResponse(content_type='application/pdf;')
    response['Content-Disposition'] = 'inline; filename=list_people.pdf'
    response['Content-Transfer-Encoding'] = 'binary'
    with tempfile.NamedTemporaryFile(delete=True) as output:
        output.write(result)
        output.flush()
        output = open(output.name, 'r')
        response.write(output.read())

    return response

templates/case.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PDF</title>
</head>
<body>
    <a href="{% url 'case_download' pk=case.pk %}">Download</a>

    <h1 style="text-align: center">{{ case.title }}</h1>

    <p>{{ case.summary }}</p>

    <p>{{ case.type }}</p>

    <div>

        <div style="left: 44pt; width: 245pt; top: 90pt; height: 632pt;">

            {% for this in case.this_set.all %}

                <p>{{ this }}</p>

            {% endfor %}

        </div>

        <div style="left: 323pt; width: 245pt; top: 90pt; height: 632pt;">

            {% for that in case.that_set.all %}

                <p>{{ that }}</p>

            {% endfor %}

        </div>
    </div>
</body>
</html>

templates/case_download.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PDF</title>

</head>
<body>
    <h1 style="text-align: center">{{ case.title }}</h1>

    <p>{{ case.summary }}</p>

    <p>{{ case.type }}</p>

    <div class="w3-container">

        <div class="w3-half">

            {% for this in case.this_set.all %}

                <p>{{ this }}</p>

            {% endfor %}

        </div>


        <div class="w3-half">

            {% for that in case.that_set.all %}

                <p>{{ that }}</p>

            {% endfor %}

        </div>
    </div>

</body>
</html>

templates/index.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PDF</title>
</head>
<body>
    <link rel="stylesheet" href="{% static 'w3.css' %}">

    <h1 class="w3-center">Cases</h1>

    {% for case in cases %}
        <div>

            <a href="{% url 'case' pk=case.pk %}">{{ case.title }}</a>

        </div>

    {% endfor %}


</body>
</html>

templates/query.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{% load data_interrogator %}

{% lineup %} {# loads the form for selecting columns #}
{% interrogation_room %} {# loads the table where data is displayed #}

</body>
</html>